### ISSUE TITLE
Missing info: a01 Node.js links invalid

### ISSUE THREAD

**Issue by YinuoLiu0708** [comp426-2023-spring/a01#3] opened 2023-01-23 18:23 UTC
#### URL of file with the missing/incorrect info
https://github.com/comp426-2023-spring/a01

#### Line number with missing or incorrect info
a0 1 Readme Instruction part

#### What is wrong?
The links directing to Node.js learning pages are all invalid.

**Comment by jdmar3** [comment] 2023-01-24 18:25
This is a duplicate of #2. I will follow up there.

**Closed as completed by jdmar3** 2023-01-24 18:25 UTC
Labels: documentation, duplicate, question
